### PR TITLE
Dept 12 search results

### PR DESCRIPTION
**Pull request by agonxalez**

### CODE REVIEW

**Comment by nkhorvash** [comment]
This looks great! I have two questions, that I'm not sure if anything needs to be done about, and just want to know what you think, and everything else looks spot on to me.

1. space between Search Results <a> element and the search bar: there are so many different figma designs with different spacing that make this confusing to me. Based on what Kathleen said this morning, I went back to the [original figma from dept](https://www.figma.com/file/DaudrLIYKfMRXKeTSFI8Iy/Shoutout---Rocket?node-id=104%3A956&t=Um17IWj4mlHPvWsm-0) > prototypes > phase 1a and it had a 67px gap between them (a little more than in this branch). But I'm not completely sure that's what we're supposed to go by since it's an older phase of the project.

2. It's really cool that you got the search query parameters in the url for search results. If I perform a few searches without leaving the search results page, the url updates, and it also updates if I navigate back and forward, but the results displayed do not update to match the url when clicking back or forward. Is this expected behavior?

**Comment by nkhorvash** [comment]
If my question 2 above about the results not updating as a user navigates forward and backward is related to how the search is built and its results saved, that might not be in the scope of this card to change. I think it might be up to you if you want to add it to this card or create a new card for that.

**Review by blamboy090 — COMMENTED** [review]
Looks great, but I have the same concern as @nkhorvash regarding the spacing

**Review by nkhorvash — APPROVED** [review]
The spacing looks good, and that issue mentioned will now be a separate card. This card is good to go.

**Review by blamboy090 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
