### PR TITLE
DEPT 77 sitewide accessibility MVP

### PR DESCRIPTION
**Pull request by nkhorvash**
This is just an MVP for accessibility. There is more that can be done, but for this card, refer to the MVP section of the [web accessibility document](https://catalystit.atlassian.net/wiki/spaces/DEPT/pages/2647359515/Web+Accessibility?atlOrigin=eyJpIjoiMjI4NjBlMTU0OTFhNDBhMWI5YjYyNzdlYzViMTg3NGUiLCJwIjoiaiJ9)

### CODE REVIEW

**Review by bdurel — COMMENTED** [review]
Great work, Naysan. Imagine there was a lot to learn on this one and that it was worthwhile. I'm learning quite a bit just from reviewing it. I've got some questions, but they really come from a place of inexperience, so they might all be underthought, overthought or somewhere in between. 🤷 So here goes... 
1. Should the team and country icons on the user profile page be picked up by a screen reader? It seems like everything else on the page is, but those aren't. 
image

2. Also regarding the H2, the screenreader says "Pewsus Heading Two." 😄 Maybe that's par for the course though?
image

3. On search results, would it make sense for the names to be tabbable, and therefore picked up by a screen reader? If I'm using a screen reader and tabbing all I hear is "see profile." If I was blind, I wouldn't know what any of the see profile buttons directed to without hearing a person's name.
image

Otherwise all looks good to me!

**Comment by nkhorvash** [comment]
These are all great questions @bdurel ! 
1. Not on these. These icons are only decorative, so the aria-hidden = true is what's recommended. The meaning comes from the text next to them.
2. Ugh, I remember wondering about that at one point, but was more focused on other AC. I'll take another pass at it.
3. Really great point that I didn't even think of. I assumed the screen reader would pickup the name next to it, but you can't tab to the name. That should be an easy fix with a big impact.

**Comment by nkhorvash** [comment]
@bdurel After looking over the app and using a screen reader, here is my updated response:
1. Those icons actually aren't just decorative, because without them, it might be hard to intuit what those acronyms mean. Therefore, I added an Aria label.
2. When I listened to the screen reader on this line, it's fast, but I think that's the way it goes. It did read each letter individually, which is what we want.
3. When a screen reader reads the page, it will read the name and then the button. We don't want it to be repetitive by reading the name, then the name (again) and see profile). I do think this interface could be improved, but I think this is good for the MVP.

**Comment by bdurel** [comment]
👍 That all sounds good to me. Passes my review.

**Review by lsanchezcode — APPROVED** [review]
LGTM! :)

**Pull request merged**
