### PR TITLE
Dept 104 create dashboard button

### PR DESCRIPTION
**Pull request by lsanchezcode**

### CODE REVIEW

**Review by blamboy090 — CHANGES_REQUESTED** [review]
The Dashboard button does not seem to be implemented on the header

**Comment by lsanchezcode** [comment]
Hi @blamboy090 I don't quite know what you mean by it not being in the header? :o 
The button is called in the `layout.tsx` files in a thing called header there along with the other two buttons. AC has been updated!

**Review by blamboy090 — CHANGES_REQUESTED** [review]
Button is now present, but branch does not appear to be up to date with sprint-3, youll want to rebase again

**Review by Incarnate-Infinity — CHANGES_REQUESTED** [review]
The button looks good and is working/showing up as expected! That said, I note that the global shoutouts widget in sprint-3 is missing from the dashboard page, so another rebase may need to occur

**Review by Incarnate-Infinity — APPROVED** [review]
LGTM 👍

**Pull request merged**
