### PR TITLE
Dept 75 bugfix refactor search results page

### PR DESCRIPTION
**Pull request by bdurel**

### CODE REVIEW

**Review by blamboy090 — CHANGES_REQUESTED** [review]
As pictured below I am seeing some page break down on various resolutions on the search page, (the break down in the dept heading component  may need to be addressed separately)
dept-75-review-1
dept-75-review-2
dept-75-review-3

**Comment by bdurel** [comment]
Good catch, Ben. This issue appears to be on the landing page as well as the user profile, so I think that would make it a separate bugfix card. 
image

**Comment by bdurel** [comment]
...appears to have to do with the odd dimensions of the app's body element

**Review by blamboy090 — APPROVED** [review]

**Review by lsanchezcode — APPROVED** [review]
lgtm! :)

**Pull request merged**
