### PR TITLE
DEPT 39 Background Image sometimes cuts off on user profile page

### PR DESCRIPTION
**Pull request by Incarnate-Infinity**

### CODE REVIEW

**Comment by blamboy090** [comment]
I am still seeing the background being cut off on this branch, Im not sure if this matters but my resolution is 1920 x 1080 which allows me to see a lot more of the background

cutoff

**Comment by blamboy090** [comment]
> I am still seeing the background being cut off on this branch, Im not sure if this matters but my resolution is 1920 x 1080 which allows me to see a lot more of the background
> 
> cutoff

Resolved, excellent work!

**Comment by bdurel** [comment]
Hey Devon, I'm seeing the bug on the received page. I think your fix was similar to what I did when Ben initially pointed this out to me. I fixed it on the received tab, but that just moved it to the given tab. Unless I'm mistaken the bug has been moved back to the received tab.
image
image

**Comment by bdurel** [comment]
The bug actually might not be related to tabs. It might be related to zero shoutouts?

**Pull request merged**
