### PR TITLE
added see profile button with test

### PR DESCRIPTION
**Pull request by agonxalez**

### CODE REVIEW

**Review by bdurel — CHANGES_REQUESTED** [review]
Nice work, Alberto. Code looks clean, meets standards.  Just one note. The button breaks down at 280width, which is the smallest mobile device we need to account for:
image
Besides that, I think it looks good. Depending on when my styling tech debt gets merged in, you'll also have some merge conflicts to address too, but for now it's fine.

**Review by blamboy090 — CHANGES_REQUESTED** [review]
Same note as Brian, the button breaks down at lower resolutions

**Review by blamboy090 — APPROVED** [review]

**Comment by bdurel** [comment]
Alberto, I've got a few more notes. It looks like some changes need to be made since you last merged in sprint-2. 

1. I'm getting a font import error when I open search results. We are now importing all fonts through the head in _document.tsx, so we don't want to use @font-face anymore.  They can just be removed from your scss, and everything should function fine. 
2. Besides that, I think there's some file structure changes to make. 
- The see-shoutouts component is part of the search result component, right? I think it makes more sense to put it in the components/search-result directory. 
- And for naming standards, "SearchShoutouts.module.scss" needs to be renamed as "see-shoutouts.module.scss." 
- This isn't on your card, but the scss file in the search-result directory is also name in camel but should be in kebab-case.
- The primary component in a component should be named index (just like page names), whereas subcomponent have specific names (in both search-result and see-shoutout, the primary component is named the same name as the folder (see shoutouts-temp and user-profile for naming examples)

**Comment by bdurel** [comment]
- Since see-shoutouts is a descendant of search-result/index, I think that see-shoutouts should be in search-result as a top level file like the other descendants of search-result/index (i.e search-result/see-shoutouts.tsx with the test you made in search-result/__test__). 
- If we're going to have multiple test files within each test folder, we need to settle on team naming standards, because we never created them for tests. All previous components only have one testing file per directory. I think having multiple testing files is better (easier to reuse code). What do you think? If we have multiple test files for each subcomponent within each testing directory, should the naming match the component file names (i.e. should the primary/parent component's test be renamed index)? 
- I'm also wondering about the multiple scss modules for each component.  I think the way you have it makes sense - multiple modules. When I componentized the user-profile, I kept them all in one module. I think I should ask Kathleen about creating a card for user-profile modules to be broken out into multiple files. Your thoughts?

**Review by bdurel — APPROVED** [review]

**Comment by bdurel** [comment]
LGTM

**Pull request merged**
