### PR TITLE
Dept 62 dashboard api

### PR DESCRIPTION
**Pull request by Incarnate-Infinity**
~~As a note, there's an additional branch `dept-62qa-make-call` that adds in an useSWR call on the landing page to actually call the dashboard API, such that the completed data object can be examined in the network tab. As this call isn't useful in that place, the statement is not present in the actual branch-to-merge. It's just for QA's convenience.~~
_Edit: With the dashboard page available, this feature has been adjusted so that said page is making the API call in the branch proper. The QA branch is thereby no longer needed, and functionality should be able to be confirmed directly._

Adds in API to make a call to the full back end, then process the received data into an object containing useful subsections of the information, as well as a source mapping of the data. As a note, JSON does not seem willing to return a proper hashmap, so the API is instead returning mapping-friendly objects that should be able to be quickly and easily converted into hashmaps on the front end, so we can leverage the lookup speed and other tools of a map as had been suggested.

### CODE REVIEW

**Comment by Incarnate-Infinity** [comment]
Holding off on this for a sec so I can configure the API call to be made from the new dashboard page.

**Review by bdurel — CHANGES_REQUESTED** [review]
Hey Devon, I'm impressed. Really a great job - clean code, easy to follow along with the api call, reducer and tests, and most importantly, works as expected. The only thing I came across to consider changing is the comments. Maybe consider not using jsdocs for the comment style, since this is the only place in the project where it's being used? On the other hand, I really do appreciate you spelling out the params and return as clearly as you did on lines 45-49, so if you do change the style I hope you keep the content of those comments.

**Comment by Incarnate-Infinity** [comment]
> Hey Devon, I'm impressed. Really a great job - clean code, easy to follow along with the api call, reducer and tests, and most importantly, works as expected. The only thing I came across to consider changing is the comments. Maybe consider not using jsdocs for the comment style, since this is the only place in the project where it's being used? On the other hand, I really do appreciate you spelling out the params and return as clearly as you did on lines 45-49, so if you do change the style I hope you keep the content of those comments.

That makes sense. Is there a preferred commenting structure for the params and such? I took a look through the project and realized that I'm not sure we've commented _any_ of our components or methods, so I'm not certain what structure (if any) I should go for. I can always just convert them to regular `//` comment lines if we think that would work better, but doing that strikes me as a bit odd personally, and I feel it would lose a lot of the functionality that the jsdocs commenting structure provides.

**Comment by bdurel** [comment]
That all makes sense to me Devon. I think it's fine to use jsdocs in this case. I was just imagining everything with just that stripped down `//` for aesthetic consistency, but it isn't in the team standards, and you're right that there's a lot of useful ino built into that structure. So it passes for me. 👍

**Review by bdurel — APPROVED** [review]

**Review by lsanchezcode — APPROVED** [review]
LGTM! :)

**Pull request merged**
