### PR TITLE
Dept 92 bugfix inter font

### PR DESCRIPTION
**Pull request by bdurel**
Simple bugfix

### CODE REVIEW

**Review by blamboy090 — CHANGES_REQUESTED** [review]
Not sure if its necessary due to the nature of the changes made but recent changes to sprint-2 are not present in this branch.  you may want to pull in sprint-2

**Comment by bdurel** [comment]
should be up to date now

**Review by blamboy090 — APPROVED** [review]
LGTM!!

**Review by Incarnate-Infinity — APPROVED** [review]
LGTM 👍

**Pull request merged**
