### PR TITLE
Dept 29 back to shoutout button update

### PR DESCRIPTION
**Pull request by lsanchezcode**
Kathleen and I decided that it would just be best to have this become a simple back button since we will be having a home button. So no matter what the button will just say back and direct you back to the previous page

### CODE REVIEW

**Review by nkhorvash — CHANGES_REQUESTED** [review]
I have a few minute details to ask about:
Figma phase 3 has font size 14px and font weight 400, which are slightly less than in the app. 
I know the app designs have changed a lot so you might have checked that with Kathleen already, but I thought I would check.
Also, the arrow is aligned to the bottom of the button, but it's aligned vertically centered in Figma.
Lastly, a mystery (same thing is occurring in the PR for dept-30 too): this branch has a console.log of the search results, but sprint-2 doesn't, and I see you've pulled in sprint-2, and somehow the conosole.log is not in the diff. It's in search-result/index.tsx line 35 .
image

**Review by blamboy090 — CHANGES_REQUESTED** [review]
Same as comments as Naysan, the font weight and font size have been changed in the phase 3 
size should be `0.875em`
weight `400`

Otherwise good work 👍

**Comment by lsanchezcode** [comment]
So @nkhorvash I tried looking for the console.log but didn't find it? I pulled again from sprint 2 but still don't see it. I am not sure why I am not seeing. 
But updated styling as well @blamboy090 :)
image

**Comment by nkhorvash** [comment]
The changes look good. I think the console.log got removed from sprint-2 recently, so it was scrubbed from your branch when you pulled sprint-2 again. I had this before pulling your branch again a minute ago. Same thing happened in dept-30.
image

**Review by nkhorvash — APPROVED** [review]
LGTM

**Review by blamboy090 — APPROVED** [review]
LGTM! Excellent work!

**Pull request merged**
