### PR TITLE
Dept 43 styling tech debt

### PR DESCRIPTION
**Pull request by bdurel**

### CODE REVIEW

**Review by Incarnate-Infinity — CHANGES_REQUESTED** [review]
This is looking great, but I do have a few things to note: 
- The "no shoutouts given/received" profile page messages are no longer appearing, it looks like the code for them got cut out during the componentization of the user profile page.
- In both the remote (as far as I can see) and in my local, Shoutouts.module.scss is still capitalized. As a note I recall reading somewhere/somewhen that changing capitalization on a remote git repo is very difficult, but I don't have the source for that info or a solution off hand at the moment.
- I still see the @font-face declarations in individual stylesheets. I had thought our original intention was to remove these, but I also see a commit that says "reverts font back to multiline since it was not causing the bug". Are these related? And if so, should we adjust that AC to better clarify any changes we are/aren't making on the JIRA card? If my understanding is inaccurate here just let me know!

Once these questions are addressed this should be good to go!

**Comment by nkhorvash** [comment]
Firstly, it's easy to get lost in a styling overhaul like this, it's a lot of work and everything is so interconnected which complicates things; therefore, well done!

A few small questions:
1. I also noticed font-face on a few style sheets and I wasn't sure if it was necessary. Maybe if there is a different weight on a particular page, but that should be able to be imported in the head tag. Also, if a font is being hosted by Google, we don't need the asset files in the project.
2. The search bar and login button have a negative margin-top, is there an advantage to that rather than a smaller margin-bottom on the element above?

**Comment by bdurel** [comment]
Thanks Devon, appreciate you catching all of these. The font-faces were merged in after I created my intial pull request, so I hadn't changed them. I'll have to double ccheck that next time. Should be sorted out now. Apologies for losing your messages. They're back in there now. And I think that I got the files to change case using 'git mv.' PLease take a look.

**Comment by bdurel** [comment]
Thanks for the review, Naysan. I thought I deleted those fonts from the assets, but I must have merged them back in at some point. Should be gone now. I corrected the login button, since I did some refactoring of that due to removing the absolute positioning; however I didn't touch the searchbox, so I believe that correcting neg margin on that component is not currently within the AC, but I'm going to follow up with KAthleen to see if she would like me to fix it.

**Comment by bdurel** [comment]
Thanks for the review, Naysan. I thought I deleted those fonts from the assets, but I must have merged them back in at some point. Should be gone now. I corrected the login button and search box's neg margin too.

**Review by nkhorvash — APPROVED** [review]
LGTM

**Review by Incarnate-Infinity — APPROVED** [review]
LGTM 👍

**Comment by bdurel** [comment]
Not quite good. I've go a negative margin on the logout in addition to the login that you pointed out Naysan. I realize that I did this because the logout doesn't appear on the login page but the heading appears on both. So I added the negative margin to compensate. I believe that the better practice would be to add an empty div with margin that renders if the logout button does not render on the login page. I think that makes sense. Does that make sense to you two?

**Pull request merged**
