### PR TITLE
Dept 122 Adjust application's use of usernames vs actual names

### PR DESCRIPTION
**Pull request by bdurel**

### CODE REVIEW

**Comment by nkhorvash** [comment]
The card AC says to use the username in the text of a shoutout (which might differ from the actual full name). I added a console.log to check raw data, and it looks like we're just seeing the full name in the shoutout text. I think Nawar and Jen have short usernames but Derek Vanderpool's username is the same as his full name.

**Comment by Incarnate-Infinity** [comment]
I'll second what @nkhorvash mentioned: I believe we're looking to get the username, or in this case whatever the person was called in the actual shoutout message. Should be a fairly quick adjustment, and other than that and adjusting the test this should be good to go

**Comment by bdurel** [comment]
Thanks for the clarification there! I didn't quite understand what we were aiming for. I changed the names in the shoutout text to remain as they originally appeared on slack. I also fixed the failing test. Let me know if there's anything else you see.

**Review by Incarnate-Infinity — APPROVED** [review]
LGTM 👍

**Review by nkhorvash — APPROVED** [review]
LGTM

**Pull request merged**
