### PR TITLE
Dept 46 loading spinner while in flight (Profile page)

### PR DESCRIPTION
**Pull request by blamboy090**
May need to throttle browser in dev tools to properly see
Removed hang tight on profile page

### CODE REVIEW

**Comment by nkhorvash** [comment]
On the profile page the loading spinner appears very high, at the top of the page, which is different from the other pages. Should it be moved down around where the user's shoutouts would appear?

**Comment by blamboy090** [comment]
Changed base to sprint 2
- Please check user profile page, as well as search results for loading spinner while data is in flight

**Comment by blamboy090** [comment]
> which

For the profile page it was determined that the spinner was ok where it was, since the entirety of the page is waiting for content

**Review by nkhorvash — APPROVED** [review]
This looks good 👍🏼

**Review by agonxalez — APPROVED** [review]

**Pull request merged**
